# main
verbose_main: false
main_iter_rate: 40
height: 2
look_ahead: 1
close_enough: 0.2
average_speed: 2.0

# motion
verbose_motion: true
use_ground_truth: false
qa: 3.85
qx: 1.7
qy: 0.5
qz: 1.2
enable_gps: true
r_gps_x: 0.059887325870381
r_gps_y: 0.041913361775251
r_gps_z: 0.135029890558406
enable_magnet: true
r_mgn_a: 0.000761616188698
enable_baro: true
r_bar_z: 0.032993641582004
enable_sonar: true
r_snr_z: 2.64584397764289E-05
motion_iter_rate: 20

# move
enable_move: true
verbose_move: false
Kp_lin: 0.6
Ki_lin: 0.02
Kd_lin: 0.02
Kp_z: 1
Ki_z: 0
Kd_z: 0
yaw_rate: 0.5
max_lin_vel: 2
max_z_vel: 0.5
move_iter_rate: 40

# run param used automatically and should not be written